name: Test Crate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: ubuntu-latest
            target: x86
          - runner: ubuntu-latest
            target: aarch64
          - runner: ubuntu-latest
            target: armv7
          - runner: ubuntu-latest
            target: s390x
          - runner: ubuntu-latest
            target: ppc64le
          - runner: macos-14
            target: aarch64
          - runner: windows-latest
            target: x64
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set project environment for uv to system python
        shell: bash
        run: |
          PREFIX=$(python -c "import sys; print(sys.prefix)")
          echo "UV_PROJECT_ENVIRONMENT=$PREFIX" >> $GITHUB_ENV
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Sync python using uv.lock
        run: uv sync --no-managed-python
      - name: "Build and test"
        run: uv run cargo test -- --nocapture
